// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSUQ4d5Fl4gJ_-DMF9nE9edPKPIFqT2q4',
    appId: '1:949175825891:web:efaf3666751f7887a49cd6',
    messagingSenderId: '949175825891',
    projectId: 'ismessenger-38829',
    authDomain: 'ismessenger-38829.firebaseapp.com',
    storageBucket: 'ismessenger-38829.appspot.com',
    measurementId: 'G-KHXKHJWBLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbo_SHULrrJsS4h3FYAiwcBsBq271OVVI',
    appId: '1:949175825891:android:4c130b882cf5b9bca49cd6',
    messagingSenderId: '949175825891',
    projectId: 'ismessenger-38829',
    storageBucket: 'ismessenger-38829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmlVuU_WaWrIZVopINjwMpE0WytlVeMyY',
    appId: '1:949175825891:ios:a3766612e98b61b4a49cd6',
    messagingSenderId: '949175825891',
    projectId: 'ismessenger-38829',
    storageBucket: 'ismessenger-38829.appspot.com',
    iosBundleId: 'com.example.isMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmlVuU_WaWrIZVopINjwMpE0WytlVeMyY',
    appId: '1:949175825891:ios:abd744e58baf76e1a49cd6',
    messagingSenderId: '949175825891',
    projectId: 'ismessenger-38829',
    storageBucket: 'ismessenger-38829.appspot.com',
    iosBundleId: 'com.example.isMessenger.RunnerTests',
  );
}
